### ISSUE TITLE
| QUESTION |  Dead link

### ISSUE THREAD

**Issue by mserouar** [sureatgithub/MaizePAS#1]
Hello,

I would be glad to test your tracking and spread it all over as it seems pretty accurate.
However the README link is dead.

Is there any way to send me it, or load it again ?

Thanks a lot !

**Comment by mserouar** [comment]
Simply an error in the link, wrong copy/paste with a **°**

**Comment by Boatsure** [comment]
The link has been fixed and in case of a dead link, you can go directly to the website figshare to search for this project.
